<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.506">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sangho Lee">
<meta name="dcterms.date" content="2024-04-13">

<title>A Replication of Karlan and List (2007)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hw1_questions_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw1_questions_files/libs/quarto-html/quarto.js"></script>
<script src="hw1_questions_files/libs/quarto-html/popper.min.js"></script>
<script src="hw1_questions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw1_questions_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw1_questions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw1_questions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw1_questions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw1_questions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw1_questions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Replication of Karlan and List (2007)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sangho Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 13, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Dean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the <em>American Economic Review</em> in 2007. The article and supporting data are available from the <a href="https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774">AEA website</a> and from Innovations for Poverty Action as part of <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&amp;version=4.2">Harvard’s Dataverse</a>.</p>
<p><em>What kind of problem are we solving, what is the story?</em> - I am addressing a field experiment evaluation problem focused on determining the effectiveness of different fundraising approaches in increasing donation rates. This study forms part of a project for the UC San Diego, MSBA program; MGTA 495 - Marketing Analytics course.</p>
<p><em>What is the goal of the analysis?</em> - The goal of the analysis is to develop a statistical model to compare the success rates of the three different types of fundraising letters. The model will evaluate which approach is most effective in generating donations and will provide insights into how variations in message framing can impact donor behavior. Ultimately, this analysis will help guide fundraising strategies by identifying the most effective methods for soliciting donations, thus enabling more efficient and targeted fundraising campaigns.</p>
<p><br></p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">Description</h3>
<section id="i-will-now-load-the-data-and-preview-the-first-few-rows.-since-the-data-is-in-.dta-format-im-going-to-use-the-haven-package-to-import-it-into-this-environment.-then-i-will-display-the-top-10-rows-as-a-sample." class="level4">
<h4 class="anchored" data-anchor-id="i-will-now-load-the-data-and-preview-the-first-few-rows.-since-the-data-is-in-.dta-format-im-going-to-use-the-haven-package-to-import-it-into-this-environment.-then-i-will-display-the-top-10-rows-as-a-sample.">I will now load the data and preview the first few rows. Since the data is in .dta format, I’m going to use the haven package to import it into this environment. Then, I will display the top 10 rows as a sample.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reticulate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_dta</span>(<span class="st">"karlan_list_2007.dta"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">treatment</th>
<th style="text-align: right;">control</th>
<th style="text-align: right;">ratio</th>
<th style="text-align: right;">ratio2</th>
<th style="text-align: right;">ratio3</th>
<th style="text-align: right;">size</th>
<th style="text-align: right;">size25</th>
<th style="text-align: right;">size50</th>
<th style="text-align: right;">size100</th>
<th style="text-align: right;">sizeno</th>
<th style="text-align: right;">ask</th>
<th style="text-align: right;">askd1</th>
<th style="text-align: right;">askd2</th>
<th style="text-align: right;">askd3</th>
<th style="text-align: right;">ask1</th>
<th style="text-align: right;">ask2</th>
<th style="text-align: right;">ask3</th>
<th style="text-align: right;">amount</th>
<th style="text-align: right;">gave</th>
<th style="text-align: right;">amountchange</th>
<th style="text-align: right;">hpa</th>
<th style="text-align: right;">ltmedmra</th>
<th style="text-align: right;">freq</th>
<th style="text-align: right;">years</th>
<th style="text-align: right;">year5</th>
<th style="text-align: right;">mrm2</th>
<th style="text-align: right;">dormant</th>
<th style="text-align: right;">female</th>
<th style="text-align: right;">couple</th>
<th style="text-align: right;">state50one</th>
<th style="text-align: right;">nonlit</th>
<th style="text-align: right;">cases</th>
<th style="text-align: right;">statecnt</th>
<th style="text-align: right;">stateresponse</th>
<th style="text-align: right;">stateresponset</th>
<th style="text-align: right;">stateresponsec</th>
<th style="text-align: right;">stateresponsetminc</th>
<th style="text-align: right;">perbush</th>
<th style="text-align: right;">close25</th>
<th style="text-align: right;">red0</th>
<th style="text-align: right;">blue0</th>
<th style="text-align: right;">redcty</th>
<th style="text-align: right;">bluecty</th>
<th style="text-align: right;">pwhite</th>
<th style="text-align: right;">pblack</th>
<th style="text-align: right;">page18_39</th>
<th style="text-align: right;">ave_hh_sz</th>
<th style="text-align: right;">median_hhincome</th>
<th style="text-align: right;">powner</th>
<th style="text-align: right;">psch_atlstba</th>
<th style="text-align: right;">pop_propurban</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-45</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4.5002995</td>
<td style="text-align: right;">0.0199468</td>
<td style="text-align: right;">0.0195024</td>
<td style="text-align: right;">0.0208062</td>
<td style="text-align: right;">-0.0013039</td>
<td style="text-align: right;">0.4900000</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.4464934</td>
<td style="text-align: right;">0.5277692</td>
<td style="text-align: right;">0.3175913</td>
<td style="text-align: right;">2.10</td>
<td style="text-align: right;">28517</td>
<td style="text-align: right;">0.4998072</td>
<td style="text-align: right;">0.3245278</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-25</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.9822462</td>
<td style="text-align: right;">0.0260870</td>
<td style="text-align: right;">0.0278330</td>
<td style="text-align: right;">0.0224949</td>
<td style="text-align: right;">0.0053381</td>
<td style="text-align: right;">0.4646465</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-50</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.6070213</td>
<td style="text-align: right;">0.0230482</td>
<td style="text-align: right;">0.0221589</td>
<td style="text-align: right;">0.0247435</td>
<td style="text-align: right;">-0.0025846</td>
<td style="text-align: right;">0.4081633</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.9357064</td>
<td style="text-align: right;">0.0119484</td>
<td style="text-align: right;">0.2761282</td>
<td style="text-align: right;">2.48</td>
<td style="text-align: right;">51175</td>
<td style="text-align: right;">0.7219406</td>
<td style="text-align: right;">0.1926679</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-25</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3.2814682</td>
<td style="text-align: right;">0.0206687</td>
<td style="text-align: right;">0.0247027</td>
<td style="text-align: right;">0.0126812</td>
<td style="text-align: right;">0.0120215</td>
<td style="text-align: right;">0.4646465</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.8883309</td>
<td style="text-align: right;">0.0107604</td>
<td style="text-align: right;">0.2794118</td>
<td style="text-align: right;">2.65</td>
<td style="text-align: right;">79269</td>
<td style="text-align: right;">0.9204314</td>
<td style="text-align: right;">0.4121422</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-15</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.3020148</td>
<td style="text-align: right;">0.0155979</td>
<td style="text-align: right;">0.0169713</td>
<td style="text-align: right;">0.0128866</td>
<td style="text-align: right;">0.0040847</td>
<td style="text-align: right;">0.5252525</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.7590141</td>
<td style="text-align: right;">0.1274209</td>
<td style="text-align: right;">0.4423889</td>
<td style="text-align: right;">1.85</td>
<td style="text-align: right;">40908</td>
<td style="text-align: right;">0.4160721</td>
<td style="text-align: right;">0.4399652</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">145</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-45</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.5306204</td>
<td style="text-align: right;">0.0187970</td>
<td style="text-align: right;">0.0264550</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0264550</td>
<td style="text-align: right;">0.5102041</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.8620533</td>
<td style="text-align: right;">0.0715718</td>
<td style="text-align: right;">0.3632385</td>
<td style="text-align: right;">2.92</td>
<td style="text-align: right;">61779</td>
<td style="text-align: right;">0.9413386</td>
<td style="text-align: right;">0.2008403</td>
<td style="text-align: right;">0.9623450</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">190</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-50</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.1390384</td>
<td style="text-align: right;">0.0157618</td>
<td style="text-align: right;">0.0204604</td>
<td style="text-align: right;">0.0055556</td>
<td style="text-align: right;">0.0149048</td>
<td style="text-align: right;">0.6060606</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.8829117</td>
<td style="text-align: right;">0.0974081</td>
<td style="text-align: right;">0.3764462</td>
<td style="text-align: right;">2.10</td>
<td style="text-align: right;">54655</td>
<td style="text-align: right;">0.6958798</td>
<td style="text-align: right;">0.5545676</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-65</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">17.3688412</td>
<td style="text-align: right;">0.0189503</td>
<td style="text-align: right;">0.0184932</td>
<td style="text-align: right;">0.0198814</td>
<td style="text-align: right;">-0.0013883</td>
<td style="text-align: right;">0.4444444</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.9032967</td>
<td style="text-align: right;">0.0194936</td>
<td style="text-align: right;">0.2120401</td>
<td style="text-align: right;">2.47</td>
<td style="text-align: right;">141527</td>
<td style="text-align: right;">0.8979058</td>
<td style="text-align: right;">0.7081225</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">315</td>
<td style="text-align: right;">375</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-100</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.3020148</td>
<td style="text-align: right;">0.0155979</td>
<td style="text-align: right;">0.0169713</td>
<td style="text-align: right;">0.0128866</td>
<td style="text-align: right;">0.0040847</td>
<td style="text-align: right;">0.5252525</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.9278508</td>
<td style="text-align: right;">0.0047386</td>
<td style="text-align: right;">0.2494650</td>
<td style="text-align: right;">2.49</td>
<td style="text-align: right;">37017</td>
<td style="text-align: right;">0.7631508</td>
<td style="text-align: right;">0.2058281</td>
<td style="text-align: right;">0.5990523</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">190</td>
<td style="text-align: right;">225</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-125</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">17.3688412</td>
<td style="text-align: right;">0.0189503</td>
<td style="text-align: right;">0.0184932</td>
<td style="text-align: right;">0.0198814</td>
<td style="text-align: right;">-0.0013883</td>
<td style="text-align: right;">0.4444444</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
</section>
<section id="i-am-also-going-to-load-the-python-packages-that-i-will-need-to-complete-the-work-in-this-environment." class="level4">
<h4 class="anchored" data-anchor-id="i-am-also-going-to-load-the-python-packages-that-i-will-need-to-complete-the-work-in-this-environment.">I am also going to load the Python packages that I will need to complete the work in this environment.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyrsm <span class="im">as</span> rsm</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>treatment</code></td>
<td>Treatment</td>
</tr>
<tr class="even">
<td><code>control</code></td>
<td>Control</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Match ratio</td>
</tr>
<tr class="even">
<td><code>ratio2</code></td>
<td>2:1 match ratio</td>
</tr>
<tr class="odd">
<td><code>ratio3</code></td>
<td>3:1 match ratio</td>
</tr>
<tr class="even">
<td><code>size</code></td>
<td>Match threshold</td>
</tr>
<tr class="odd">
<td><code>size25</code></td>
<td>$25,000 match threshold</td>
</tr>
<tr class="even">
<td><code>size50</code></td>
<td>$50,000 match threshold</td>
</tr>
<tr class="odd">
<td><code>size100</code></td>
<td>$100,000 match threshold</td>
</tr>
<tr class="even">
<td><code>sizeno</code></td>
<td>Unstated match threshold</td>
</tr>
<tr class="odd">
<td><code>ask</code></td>
<td>Suggested donation amount</td>
</tr>
<tr class="even">
<td><code>askd1</code></td>
<td>Suggested donation was highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>askd2</code></td>
<td>Suggested donation was 1.25 x highest previous contribution</td>
</tr>
<tr class="even">
<td><code>askd3</code></td>
<td>Suggested donation was 1.50 x highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>ask1</code></td>
<td>Highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>ask2</code></td>
<td>1.25 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="odd">
<td><code>ask3</code></td>
<td>1.50 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>amount</code></td>
<td>Dollars given</td>
</tr>
<tr class="odd">
<td><code>gave</code></td>
<td>Gave anything</td>
</tr>
<tr class="even">
<td><code>amountchange</code></td>
<td>Change in amount given</td>
</tr>
<tr class="odd">
<td><code>hpa</code></td>
<td>Highest previous contribution</td>
</tr>
<tr class="even">
<td><code>ltmedmra</code></td>
<td>Small prior donor: last gift was less than median $35</td>
</tr>
<tr class="odd">
<td><code>freq</code></td>
<td>Number of prior donations</td>
</tr>
<tr class="even">
<td><code>years</code></td>
<td>Number of years since initial donation</td>
</tr>
<tr class="odd">
<td><code>year5</code></td>
<td>At least 5 years since initial donation</td>
</tr>
<tr class="even">
<td><code>mrm2</code></td>
<td>Number of months since last donation</td>
</tr>
<tr class="odd">
<td><code>dormant</code></td>
<td>Already donated in 2005</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Female</td>
</tr>
<tr class="odd">
<td><code>couple</code></td>
<td>Couple</td>
</tr>
<tr class="even">
<td><code>state50one</code></td>
<td>State tag: 1 for one observation of each of 50 states; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>nonlit</code></td>
<td>Nonlitigation</td>
</tr>
<tr class="even">
<td><code>cases</code></td>
<td>Court cases from state in 2004-5 in which organization was involved</td>
</tr>
<tr class="odd">
<td><code>statecnt</code></td>
<td>Percent of sample from state</td>
</tr>
<tr class="even">
<td><code>stateresponse</code></td>
<td>Proportion of sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponset</code></td>
<td>Proportion of treated sample from the state who gave</td>
</tr>
<tr class="even">
<td><code>stateresponsec</code></td>
<td>Proportion of control sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponsetminc</code></td>
<td>stateresponset - stateresponsec</td>
</tr>
<tr class="even">
<td><code>perbush</code></td>
<td>State vote share for Bush</td>
</tr>
<tr class="odd">
<td><code>close25</code></td>
<td>State vote share for Bush between 47.5% and 52.5%</td>
</tr>
<tr class="even">
<td><code>red0</code></td>
<td>Red state</td>
</tr>
<tr class="odd">
<td><code>blue0</code></td>
<td>Blue state</td>
</tr>
<tr class="even">
<td><code>redcty</code></td>
<td>Red county</td>
</tr>
<tr class="odd">
<td><code>bluecty</code></td>
<td>Blue county</td>
</tr>
<tr class="even">
<td><code>pwhite</code></td>
<td>Proportion white within zip code</td>
</tr>
<tr class="odd">
<td><code>pblack</code></td>
<td>Proportion black within zip code</td>
</tr>
<tr class="even">
<td><code>page18_39</code></td>
<td>Proportion age 18-39 within zip code</td>
</tr>
<tr class="odd">
<td><code>ave_hh_sz</code></td>
<td>Average household size within zip code</td>
</tr>
<tr class="even">
<td><code>median_hhincome</code></td>
<td>Median household income within zip code</td>
</tr>
<tr class="odd">
<td><code>powner</code></td>
<td>Proportion house owner within zip code</td>
</tr>
<tr class="even">
<td><code>psch_atlstba</code></td>
<td>Proportion who finished college within zip code</td>
</tr>
<tr class="odd">
<td><code>pop_propurban</code></td>
<td>Proportion of population urban within zip code</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><br></p>
</section>
</section>
<section id="balance-test" class="level3">
<h3 class="anchored" data-anchor-id="balance-test">Balance Test</h3>
<p>As an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.</p>
<section id="im-going-to-conduct-t-tests-and-linear-regressions-on-several-variables-such-as-months-since-last-donation-to-determine-if-there-are-statistically-significant-differences-between-the-treatment-and-control-groups-at-the-95-confidence-level.-for-the-t-tests-i-will-use-the-t.test-function-in-r-to-analyze-the-data.-for-the-linear-regressions-i-will-utilize-the-pyrsm-package-in-python-to-examine-the-impact-of-the-treatment-by-regressing-variables-like-months-since-last-donation-against-the-treatment-group-and-observing-the-coefficient-of-the-treatment-variable.-this-approach-will-allow-me-to-confirm-that-both-methods-yield-consistent-results." class="level4">
<h4 class="anchored" data-anchor-id="im-going-to-conduct-t-tests-and-linear-regressions-on-several-variables-such-as-months-since-last-donation-to-determine-if-there-are-statistically-significant-differences-between-the-treatment-and-control-groups-at-the-95-confidence-level.-for-the-t-tests-i-will-use-the-t.test-function-in-r-to-analyze-the-data.-for-the-linear-regressions-i-will-utilize-the-pyrsm-package-in-python-to-examine-the-impact-of-the-treatment-by-regressing-variables-like-months-since-last-donation-against-the-treatment-group-and-observing-the-coefficient-of-the-treatment-variable.-this-approach-will-allow-me-to-confirm-that-both-methods-yield-consistent-results.">I’m going to conduct t-tests and linear regressions on several variables, such as months since last donation, to determine if there are statistically significant differences between the treatment and control groups at the 95% confidence level. For the t-tests, I will use the t.test function in R to analyze the data. For the linear regressions, I will utilize the pyrsm package in Python to examine the impact of the treatment by regressing variables like months since last donation against the treatment group and observing the coefficient of the treatment variable. This approach will allow me to confirm that both methods yield consistent results.</h4>
<ol type="1">
<li>mrm2 variable</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(mrm2 <span class="sc">~</span> treatment, <span class="at">data =</span> data, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  mrm2 by treatment
t = -0.11953, df = 33394, p-value = 0.9049
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.2381015  0.2107298
sample estimates:
mean in group 0 mean in group 1 
       12.99814        13.01183 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lm <span class="op">=</span> rsm.model.regress(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  data <span class="op">=</span> data,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  rvar <span class="op">=</span> <span class="st">"mrm2"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  evar <span class="op">=</span> <span class="st">"treatment"</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>lm.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear regression (OLS)
Data                 : Not provided
Response variable    : mrm2
Explanatory variables: treatment
Null hyp.: the effect of x on mrm2 is zero
Alt. hyp.: the effect of x on mrm2 is not zero

           coefficient  std.error  t.value p.value     
Intercept        13.00      0.094  138.979  &lt; .001  ***
treatment         0.01      0.115    0.119   0.905     

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-squared: 0.0, Adjusted R-squared: -0.0
F-statistic: 0.014 df(1, 50080), p.value 0.905
Nr obs: 50,082</code></pre>
</div>
</div>
<ul>
<li>P-value: Both methods yield a p-value of approximately 0.905</li>
<li>Interpretation: There are no significant differences between the treatment and control groups for “mrm2” (months since last donation). This suggests effective randomization, indicating that any observed treatment effects are likely due to the treatment itself rather than pre-existing group differences.</li>
</ul>
<p><br></p>
<ol start="2" type="1">
<li>pwhite variable</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(pwhite <span class="sc">~</span> treatment, <span class="at">data =</span> data, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  pwhite by treatment
t = 0.55912, df = 31876, p-value = 0.5761
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.002287046  0.004112602
sample estimates:
mean in group 0 mean in group 1 
      0.8202078       0.8192950 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lm <span class="op">=</span> rsm.model.regress(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  data <span class="op">=</span> data,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  rvar <span class="op">=</span> <span class="st">"pwhite"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  evar <span class="op">=</span> <span class="st">"treatment"</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>lm.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear regression (OLS)
Data                 : Not provided
Response variable    : pwhite
Explanatory variables: treatment
Null hyp.: the effect of x on pwhite is zero
Alt. hyp.: the effect of x on pwhite is not zero

           coefficient  std.error  t.value p.value     
Intercept         0.82      0.001  616.281  &lt; .001  ***
treatment        -0.00      0.002   -0.560   0.575     

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-squared: 0.0, Adjusted R-squared: -0.0
F-statistic: 0.314 df(1, 48215), p.value 0.575
Nr obs: 48,217</code></pre>
</div>
</div>
<ul>
<li>P-value: Both the t-test and linear regression show a p-value around 0.575.</li>
<li>Interpretation: There is no significant difference in the proportion of white individuals between the treatment and control groups, indicating that the randomization was successful in creating comparable groups regarding racial composition.</li>
</ul>
<p><br></p>
<ol start="3" type="1">
<li>female variable</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(female <span class="sc">~</span> treatment, <span class="at">data =</span> data, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  female by treatment
t = 1.7535, df = 32451, p-value = 0.07952
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.0008888548  0.0159826921
sample estimates:
mean in group 0 mean in group 1 
      0.2826978       0.2751509 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>lm <span class="op">=</span> rsm.model.regress(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  data <span class="op">=</span> data,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  rvar <span class="op">=</span> <span class="st">"female"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  evar <span class="op">=</span> <span class="st">"treatment"</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>lm.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear regression (OLS)
Data                 : Not provided
Response variable    : female
Explanatory variables: treatment
Null hyp.: the effect of x on female is zero
Alt. hyp.: the effect of x on female is not zero

           coefficient  std.error  t.value p.value     
Intercept         0.28      0.004   80.688  &lt; .001  ***
treatment        -0.01      0.004   -1.758   0.079    .

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-squared: 0.0, Adjusted R-squared: 0.0
F-statistic: 3.092 df(1, 48970), p.value 0.079
Nr obs: 48,972</code></pre>
</div>
</div>
<ul>
<li>P-value: The t-test has a p-value of 0.07952 and the linear regression also shows a p-value of 0.079.</li>
<li>Interpretation: The results suggest a marginal difference in the proportion of females between the treatment and control groups that approaches but does not reach conventional levels of statistical significance (p &lt; 0.05).</li>
</ul>
<section id="understanding-the-t-value-and-p-value" class="level5">
<h5 class="anchored" data-anchor-id="understanding-the-t-value-and-p-value">Understanding the T-value and P-value</h5>
<ul>
<li><p>T-value (1.7535): The t-value measures the ratio of the difference between the group means to the standard error of the difference. A t-value of 1.7535 indicates that the difference between the group means (for the proportion of females in treatment versus control) is 1.7535 times the standard error away from zero. The sign (+) of the t-value suggests that the mean proportion of females in the treatment group is slightly lower than in the control group, given the negative coefficient in the regression output.</p></li>
<li><p>P-value (0.07952): The p-value tells us the probability of observing a t-value as extreme as 1.7535 (or more) if the null hypothesis were true which was there is no difference in the proportion of females between groups.</p></li>
</ul>
</section>
</section>
</section>
</section>
<section id="experimental-results" class="level2">
<h2 class="anchored" data-anchor-id="experimental-results">Experimental Results</h2>
<section id="charitable-contribution-made" class="level3">
<h3 class="anchored" data-anchor-id="charitable-contribution-made">Charitable Contribution Made</h3>
<p>First, I analyze whether matched donations lead to an increased response rate of making a donation.</p>
<section id="im-going-to-create-a-bar-plot-that-visualizes-the-proportion-of-people-who-donated-with-two-separate-bars-representing-the-treatment-and-control-groups.-this-will-allow-for-a-clear-comparison-of-the-donation-rates-between-the-two-groups" class="level4">
<h4 class="anchored" data-anchor-id="im-going-to-create-a-bar-plot-that-visualizes-the-proportion-of-people-who-donated-with-two-separate-bars-representing-the-treatment-and-control-groups.-this-will-allow-for-a-clear-comparison-of-the-donation-rates-between-the-two-groups">I’m going to create a bar plot that visualizes the proportion of people who donated, with two separate bars representing the treatment and control groups. This will allow for a clear comparison of the donation rates between the two groups</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the proportion of donations in the treatment and control groups using dplyr</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(treatment) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">Proportion_Donated =</span> <span class="fu">mean</span>(gave <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Group =</span> <span class="fu">ifelse</span>(treatment <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Treatment"</span>, <span class="st">"Control"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Group, Proportion_Donated)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the bar plot using ggplot2</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> Group, <span class="at">y =</span> Proportion_Donated, <span class="at">fill =</span> Group)) <span class="sc">+</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>scales<span class="sc">::</span><span class="fu">percent</span>(Proportion_Donated)), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.3</span>, <span class="at">size=</span><span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()) <span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Proportion of Donations"</span>, <span class="at">title =</span> <span class="st">"Proportion of People Who Donated by Group"</span>) <span class="sc">+</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme</span>(</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">22</span>),</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">20</span>),</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">20</span>),</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Treatment"</span> <span class="ot">=</span> <span class="st">"#FF5733"</span>, <span class="st">"Control"</span> <span class="ot">=</span> <span class="st">"#33C1FF"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="im-going-to-perform-a-t-test-to-compare-the-treatment-and-control-groups-based-on-whether-a-charitable-donation-was-made.-additionally-i-will-conduct-a-linear-regression-to-analyze-the-same-data.-after-obtaining-the-statistical-outcomes-i-will-interpret-these-results-in-the-context-of-the-experiment.-specifically-if-the-results-show-a-statistically-significant-difference-ill-discuss-what-these-findings-suggest-about-human-behavior-towards-charitable-giving-focusing-more-on-qualitative-insights-rather-than-numerical-data." class="level4">
<h4 class="anchored" data-anchor-id="im-going-to-perform-a-t-test-to-compare-the-treatment-and-control-groups-based-on-whether-a-charitable-donation-was-made.-additionally-i-will-conduct-a-linear-regression-to-analyze-the-same-data.-after-obtaining-the-statistical-outcomes-i-will-interpret-these-results-in-the-context-of-the-experiment.-specifically-if-the-results-show-a-statistically-significant-difference-ill-discuss-what-these-findings-suggest-about-human-behavior-towards-charitable-giving-focusing-more-on-qualitative-insights-rather-than-numerical-data.">I’m going to perform a t-test to compare the treatment and control groups based on whether a charitable donation was made. Additionally, I will conduct a linear regression to analyze the same data. After obtaining the statistical outcomes, I will interpret these results in the context of the experiment. Specifically, if the results show a statistically significant difference, I’ll discuss what these findings suggest about human behavior towards charitable giving, focusing more on qualitative insights rather than numerical data.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(gave <span class="sc">~</span> treatment, <span class="at">data =</span> data, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  gave by treatment
t = -3.2095, df = 36577, p-value = 0.001331
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.006733310 -0.001627399
sample estimates:
mean in group 0 mean in group 1 
     0.01785821      0.02203857 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>lm <span class="op">=</span> rsm.model.regress(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  data <span class="op">=</span> data,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  rvar <span class="op">=</span> <span class="st">"gave"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  evar <span class="op">=</span> <span class="st">"treatment"</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>lm.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear regression (OLS)
Data                 : Not provided
Response variable    : gave
Explanatory variables: treatment
Null hyp.: the effect of x on gave is zero
Alt. hyp.: the effect of x on gave is not zero

           coefficient  std.error  t.value p.value     
Intercept         0.02      0.001   16.225  &lt; .001  ***
treatment         0.00      0.001    3.101   0.002   **

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-squared: 0.0, Adjusted R-squared: 0.0
F-statistic: 9.618 df(1, 50081), p.value 0.002
Nr obs: 50,083</code></pre>
</div>
</div>
</section>
<section id="the-t-test-and-linear-regression-both-show-that-the-treatment-group-had-a-slightly-higher-donation-rate-2.2-compared-to-the-control-group-1.8.-this-statistically-significant-difference-p-value-0.0013-for-the-t-test-suggests-that-even-a-modest-intervention-can-effectively-increase-the-likelihood-of-donating.-this-demonstrates-how-small-nudges-such-as-targeted-reminders-can-influence-human-behavior-and-enhance-donation-rates-which-is-crucial-for-organizations-aiming-to-improve-their-fundraising-outcomes." class="level4">
<h4 class="anchored" data-anchor-id="the-t-test-and-linear-regression-both-show-that-the-treatment-group-had-a-slightly-higher-donation-rate-2.2-compared-to-the-control-group-1.8.-this-statistically-significant-difference-p-value-0.0013-for-the-t-test-suggests-that-even-a-modest-intervention-can-effectively-increase-the-likelihood-of-donating.-this-demonstrates-how-small-nudges-such-as-targeted-reminders-can-influence-human-behavior-and-enhance-donation-rates-which-is-crucial-for-organizations-aiming-to-improve-their-fundraising-outcomes.">The t-test and linear regression both show that the treatment group had a slightly higher donation rate (2.2%) compared to the control group (1.8%). This statistically significant difference (p-value = 0.0013 for the t-test) suggests that even a modest intervention can effectively increase the likelihood of donating. This demonstrates how small nudges, such as targeted reminders, can influence human behavior and enhance donation rates, which is crucial for organizations aiming to improve their fundraising outcomes.</h4>
<p><br></p>
</section>
<section id="im-going-to-conduct-a-probit-regression-where-the-outcome-variable-is-whether-a-charitable-donation-was-made-and-the-explanatory-variable-is-whether-individuals-were-assigned-to-the-treatment-or-control-group." class="level4">
<h4 class="anchored" data-anchor-id="im-going-to-conduct-a-probit-regression-where-the-outcome-variable-is-whether-a-charitable-donation-was-made-and-the-explanatory-variable-is-whether-individuals-were-assigned-to-the-treatment-or-control-group.">I’m going to conduct a probit regression where the outcome variable is whether a charitable donation was made, and the explanatory variable is whether individuals were assigned to the treatment or control group.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the dependent and independent variables</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> data[[<span class="st">'treatment'</span>]]  <span class="co"># independent variable</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)  <span class="co"># adding a constant</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> data[<span class="st">'gave'</span>]  <span class="co"># dependent variable</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a probit model</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>probit_model <span class="op">=</span> sm.Probit(y, X).fit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.100443
         Iterations 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary of the model</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(probit_model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Probit Regression Results                           
==============================================================================
Dep. Variable:                   gave   No. Observations:                50083
Model:                         Probit   Df Residuals:                    50081
Method:                           MLE   Df Model:                            1
Date:                Sat, 13 Apr 2024   Pseudo R-squ.:               0.0009783
Time:                        02:03:18   Log-Likelihood:                -5030.5
converged:                       True   LL-Null:                       -5035.4
Covariance Type:            nonrobust   LLR p-value:                  0.001696
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.1001      0.023    -90.073      0.000      -2.146      -2.054
treatment      0.0868      0.028      3.113      0.002       0.032       0.141
==============================================================================</code></pre>
</div>
</div>
<p><br></p>
<ul>
<li>Probit Regression Explained: Probit regression is a type of regression used in statistics to analyze binary (two outcome) variables. In this context, it models the probability that someone made a charitable donation based on whether they were in the treatment group or not.</li>
</ul>
<p>Key Elements of the Output:</p>
<ul>
<li><p>Dependent Variable (gave): This is what we’re trying to predict: whether or not someone gave a donation (1 if yes, 0 if no).</p></li>
<li><p>Number of Observations (50,083): This is the total number of data points used in the model.</p></li>
<li><p>Model (Probit): The type of model used, which in this case uses a Probit link function. This function maps any input from minus infinity to infinity to a 0 to 1 range, fitting the binary nature of the dependent variable.</p></li>
<li><p>MLE (Maximum Likelihood Estimation): This is the method used to fit the model, optimizing to find the parameter values that maximize the likelihood of the data given the model.</p></li>
<li><p>Coefficients:</p></li>
</ul>
<ol type="1">
<li>const (-2.1001): This is the intercept, or baseline log odds of donating when all predictors are 0 (i.e., not in the treatment group). A negative value indicates a low baseline probability of donation.</li>
<li>treatment (0.0868): This coefficient shows the effect of being in the treatment group. It suggests that being in the treatment group increases the likelihood of donating compared to the control group.</li>
</ol>
<ul>
<li><p>Standard Error (std err): These values (0.023 for const and 0.028 for treatment) measure the average distance that the estimated values (coefficients) fall from the actual value. Smaller standard errors suggest more precise estimates.</p></li>
<li><p>Z-value: This is the test statistic used to determine whether to reject the null hypothesis (that the coefficient is zero, implying no effect). For the treatment, a z-value of 3.113 indicates a statistically significant effect.</p></li>
<li><p>P-value: For treatment (0.002), this value is very small, indicating strong evidence against the null hypothesis. It suggests that the treatment effect is statistically significant and not due to random chance.</p></li>
<li><p>Confidence Interval: For treatment ([0.032, 0.141]), this range gives us a 95% confidence level that the true coefficient falls within this interval. It confirms that the effect is positive and fairly precise.</p></li>
</ul>
<p><br><br></p>
</section>
</section>
<section id="differences-between-match-rates" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates">Differences between Match Rates</h3>
<p>Next, I assess the effectiveness of different sizes of matched donations on the response rate.</p>
<section id="now-i-will-perform-a-series-of-t-tests-to-evaluate-whether-different-match-ratios-influence-the-likelihood-of-making-a-donation.-specifically-ill-compare-the-donation-rates-under-a-21-match-ratio-to-those-under-a-11-match-ratio." class="level4">
<h4 class="anchored" data-anchor-id="now-i-will-perform-a-series-of-t-tests-to-evaluate-whether-different-match-ratios-influence-the-likelihood-of-making-a-donation.-specifically-ill-compare-the-donation-rates-under-a-21-match-ratio-to-those-under-a-11-match-ratio.">Now, I will perform a series of t-tests to evaluate whether different match ratios influence the likelihood of making a donation. Specifically, I’ll compare the donation rates under a 2:1 match ratio to those under a 1:1 match ratio.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>group_1_1 <span class="ot">&lt;-</span> data[data<span class="sc">$</span>ratio <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"gave"</span>]  <span class="co"># Adjust 'ratio' to the actual column name for 1:1 match</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>group_2_1 <span class="ot">&lt;-</span> data[data<span class="sc">$</span>ratio2 <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"gave"</span>] <span class="co"># Adjust 'ratio2' to the actual column name for 2:1 match</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test between 1:1 match rate and 2:1 match rate</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>t_test_1_1_vs_2_1 <span class="ot">&lt;-</span> <span class="fu">t.test</span>(group_1_1, group_2_1, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>t_test_1_1_vs_2_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  group_1_1 and group_2_1
t = -0.96505, df = 22265, p-value = 0.3345
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.005711282  0.001942780
sample estimates:
 mean of x  mean of y 
0.02074912 0.02263338 </code></pre>
</div>
</div>
</section>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation:</h3>
<ul>
<li><p>T-value Interpretation: In this context, a t-value of -0.96505 indicates a relatively small difference in donation rates between the two match ratios, which is not statistically significant.</p></li>
<li><p>P-value Interpretation: The p-value of 0.3345 indicates that there is not a statistically significant difference between the donation rates of the 1:1 and 2:1 match ratios at the conventional 0.05 significance level. This means that the null hypothesis (that there is no difference in means) cannot be rejected based on the data provided.</p></li>
<li><p>Mean Donation Rates: The mean donation rate for the 1:1 match ratio group (mean of x) is approximately 2.07%, and for the 2:1 match ratio group (mean of y), it’s approximately 2.26%. Although the 2:1 match ratio shows a higher mean donation rate, the difference is not statistically significant based on the t-test results.</p></li>
<li><p>Confidence Interval: The confidence interval ranges from about -0.57% to +0.19%. Since this interval includes zero, it further supports the conclusion that we cannot assert a significant difference in donation rates between these two groups. The interval suggests that the true difference could range from a slight decrease to a slight increase when moving from a 1:1 to a 2:1 match.</p></li>
<li><p>Conclusion: The analysis does not provide evidence that increasing the match ratio from 1:1 to 2:1 significantly increases the likelihood that someone donates.</p></li>
</ul>
<p><br><br></p>
<section id="now-im-going-to-analyze-the-impact-of-different-match-ratios-on-the-likelihood-of-donations-using-regression-analysis.-ill-create-a-variable-called-ratio1-and-then-regress-the-binary-outcome-gave-on-ratio1-ratio2-and-ratio3.-alternatively-i-could-use-a-single-categorical-variable-ratio-to-perform-the-regression.-after-obtaining-the-regression-coefficients-i-will-interpret-their-significance-and-statistical-precision-to-understand-the-influence-of-match-ratios-on-donation-behavior." class="level4">
<h4 class="anchored" data-anchor-id="now-im-going-to-analyze-the-impact-of-different-match-ratios-on-the-likelihood-of-donations-using-regression-analysis.-ill-create-a-variable-called-ratio1-and-then-regress-the-binary-outcome-gave-on-ratio1-ratio2-and-ratio3.-alternatively-i-could-use-a-single-categorical-variable-ratio-to-perform-the-regression.-after-obtaining-the-regression-coefficients-i-will-interpret-their-significance-and-statistical-precision-to-understand-the-influence-of-match-ratios-on-donation-behavior.">Now, I’m going to analyze the impact of different match ratios on the likelihood of donations using regression analysis. I’ll create a variable called ratio1 and then regress the binary outcome gave on ratio1, ratio2, and ratio3. Alternatively, I could use a single categorical variable ratio to perform the regression. After obtaining the regression coefficients, I will interpret their significance and statistical precision to understand the influence of match ratios on donation behavior.</h4>
<p><em>Data Preparation</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function that applies the conditions to create the new `ratio1` values</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_ratio1(row):</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> row[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"1:1"</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> row[<span class="st">'ratio2'</span>] <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"2:1"</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> row[<span class="st">'ratio3'</span>] <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"3:1"</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">"No Match"</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the function along the rows (axis=1) to create a new 'ratio1' column</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'ratio1'</span>] <span class="op">=</span> data.<span class="bu">apply</span>(calculate_ratio1, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'ratio1'</span>] <span class="op">=</span> data[<span class="st">'ratio1'</span>].astype(<span class="st">'category'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Run the logistic regression model</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> rsm.model.logistic(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  data <span class="op">=</span> data,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  rvar <span class="op">=</span> <span class="st">"gave"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  lev <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  evar <span class="op">=</span> <span class="st">"ratio1"</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>model.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Logistic regression (GLM)
Data                 : Not provided
Response variable    : gave
Level                : 1
Explanatory variables: ratio1
Null hyp.: There is no effect of x on gave
Alt. hyp.: There is an effect of x on gave

                     OR     OR%  coefficient  std.error  z.value p.value     
Intercept         0.021  -97.9%        -3.85      0.066  -57.969  &lt; .001  ***
ratio1[2:1]       1.093    9.3%         0.09      0.092    0.965   0.335     
ratio1[3:1]       1.098    9.8%         0.09      0.092    1.015    0.31     
ratio1[No Match]  0.858  -14.2%        -0.15      0.089   -1.728   0.084    .

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Pseudo R-squared (McFadden): 0.001
Pseudo R-squared (McFadden adjusted): 0.001
Area under the RO Curve (AUC): 0.528
Log-likelihood: -5029.849, AIC: 10067.699, BIC: 10102.984
Chi-squared: 11.156, df(3), p.value 0.011 
Nr obs: 50,083</code></pre>
</div>
</div>
<section id="this-logistic-regression-results-focus-on-assessing-the-impact-of-different-match-ratios-11-21-31-and-no-match-on-the-likelihood-of-making-a-donation-gave.-lets-discuss-and-interpret-each-part-of-the-output" class="level5">
<h5 class="anchored" data-anchor-id="this-logistic-regression-results-focus-on-assessing-the-impact-of-different-match-ratios-11-21-31-and-no-match-on-the-likelihood-of-making-a-donation-gave.-lets-discuss-and-interpret-each-part-of-the-output">This logistic regression results focus on assessing the impact of different match ratios (1:1, 2:1, 3:1, and no match) on the likelihood of making a donation (gave). Let’s discuss and interpret each part of the output:</h5>
</section>
<section id="model-overview" class="level5">
<h5 class="anchored" data-anchor-id="model-overview">Model Overview</h5>
<ul>
<li>Model Type: Logistic regressionw which models the probability of the outcome variable (gave).</li>
<li>Response Variable: gave (whether a donation was made, presumably coded as 1 for yes and 0 for no).</li>
<li>Explanatory Variables: ratio1, categorized into 1:1, 2:1, 3:1, and No Match.</li>
</ul>
</section>
<section id="coefficients-and-their-interpretation" class="level5">
<h5 class="anchored" data-anchor-id="coefficients-and-their-interpretation">Coefficients and Their Interpretation</h5>
<ul>
<li>Intercept (-3.85): This is the log-odds of giving when all explanatory variables are at their baseline level (likely when ratio1[No Match] is the reference category, based on typical coding). The very negative intercept suggests a very low baseline probability of donating when no match is offered.</li>
<li>ratio1[2:1] (0.09): Indicates a slight increase in the log odds of donating under the 2:1 match ratio compared to no match, but with a p-value of 0.335, this increase is not statistically significant.</li>
<li>ratio1[3:1] (0.09): Similar to the 2:1 match, the 3:1 match shows a minimal effect on the log odds of donating and is also not statistically significant (p-value of 0.31).</li>
<li>ratio1[No Match] (-0.15): This coefficient, if the coding were such that another category were the baseline, would suggest a decrease in the likelihood of donating compared to the baseline.</li>
</ul>
</section>
<section id="statistical-precision" class="level5">
<h5 class="anchored" data-anchor-id="statistical-precision">Statistical Precision</h5>
<ul>
<li>Standard Errors: Reflect the precision of the estimated coefficients. The larger the standard error, the less precise the estimate. Here, the standard errors are relatively small but not sufficiently so to produce significant results for the 2:1 and 3:1 match ratios.</li>
<li>Z-values and P-values: These assess the statistical significance of each coefficient. None of the match ratios shows a p-value under the traditional 0.05 threshold for significance, suggesting that there is no strong evidence that either the 2:1 or 3:1 match ratios significantly increase the likelihood of donating compared to no match.</li>
</ul>
</section>
<section id="model-fit-and-quality" class="level5">
<h5 class="anchored" data-anchor-id="model-fit-and-quality">Model Fit and Quality</h5>
<ul>
<li>Pseudo R-squared (McFadden): Very low (0.001), indicating that the model does not explain much of the variance in the response variable beyond the baseline model.</li>
<li>AUC (0.528): Slightly better than a coin flip, indicating the model has very limited ability to discriminate between those who gave and those who did not based on the match ratio.</li>
<li>Chi-squared and its p-value (0.011): While the overall model test suggests some level of significance, the lack of significance in individual predictors and the very low explanatory power suggest that match ratios, as modeled, are not strong predictors of donation behavior.</li>
</ul>
</section>
<section id="conclusion" class="level5">
<h5 class="anchored" data-anchor-id="conclusion">Conclusion</h5>
<ul>
<li>The analysis shows that there is no compelling evidence from this logistic regression model that increasing the match ratio from no match to either a 2:1 or a 3:1 ratio significantly increases the probability of making a donation. This finding could suggest that either the size of the match is not sufficiently motivating to change donor behavior, or that other factors not included in the model are more influential in determining whether individuals donate.</li>
</ul>
<p><br><br></p>
</section>
</section>
<section id="i-need-to-calculate-the-response-rate-differences-between-the-11-and-21-match-ratios-and-also-between-the-21-and-31-match-ratios.-first-ill-determine-these-differences-directly-from-the-dataset.-then-ill-compute-the-differences-using-the-fitted-coefficients-from-the-previous-regression-analysis.-this-dual-approach-will-help-me-draw-conclusions-about-the-effectiveness-of-various-match-donation-sizes-in-influencing-donation-behavior." class="level4">
<h4 class="anchored" data-anchor-id="i-need-to-calculate-the-response-rate-differences-between-the-11-and-21-match-ratios-and-also-between-the-21-and-31-match-ratios.-first-ill-determine-these-differences-directly-from-the-dataset.-then-ill-compute-the-differences-using-the-fitted-coefficients-from-the-previous-regression-analysis.-this-dual-approach-will-help-me-draw-conclusions-about-the-effectiveness-of-various-match-donation-sizes-in-influencing-donation-behavior.">I need to calculate the response rate differences between the 1:1 and 2:1 match ratios, and also between the 2:1 and 3:1 match ratios. First, I’ll determine these differences directly from the dataset. Then, I’ll compute the differences using the fitted coefficients from the previous regression analysis. This dual approach will help me draw conclusions about the effectiveness of various match donation sizes in influencing donation behavior.</h4>
<p><em>Method 1: Direct Calculation from Data</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate response rates directly from the data</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>response_rate_1_1 <span class="op">=</span> data[data[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>].mean()</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>response_rate_2_1 <span class="op">=</span> data[data[<span class="st">'ratio2'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>].mean()</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>response_rate_3_1 <span class="op">=</span> data[data[<span class="st">'ratio3'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>].mean()</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate differences</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>difference_1_1_to_2_1 <span class="op">=</span> response_rate_2_1 <span class="op">-</span> response_rate_1_1</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>difference_2_1_to_3_1 <span class="op">=</span> response_rate_3_1 <span class="op">-</span> response_rate_2_1</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Difference in response rate from 1:1 to 2:1: </span><span class="sc">{</span>difference_1_1_to_2_1<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Difference in response rate from 1:1 to 2:1: 0.0018842510217149944</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Difference in response rate from 2:1 to 3:1: </span><span class="sc">{</span>difference_2_1_to_3_1<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Difference in response rate from 2:1 to 3:1: 0.00010002398025293902</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients from the logistic regression model</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>coef_1_1 <span class="op">=</span> <span class="dv">0</span>  <span class="co"># Baseline category (if 1:1 is baseline and not explicitly shown in output)</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>coef_2_1 <span class="op">=</span> <span class="fl">0.09</span>  <span class="co"># From the model results for 2:1</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>coef_3_1 <span class="op">=</span> <span class="fl">0.09</span>  <span class="co"># From the model results for 3:1</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate differences in log-odds</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>log_odds_difference_1_1_to_2_1 <span class="op">=</span> coef_2_1 <span class="op">-</span> coef_1_1</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>log_odds_difference_2_1_to_3_1 <span class="op">=</span> coef_3_1 <span class="op">-</span> coef_2_1</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert these log-odds differences to probabilities</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>probability_difference_1_1_to_2_1 <span class="op">=</span> np.exp(log_odds_difference_1_1_to_2_1) <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(log_odds_difference_1_1_to_2_1))</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>probability_difference_2_1_to_3_1 <span class="op">=</span> np.exp(log_odds_difference_2_1_to_3_1) <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(log_odds_difference_2_1_to_3_1))</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log-odds difference from 1:1 to 2:1: </span><span class="sc">{</span>log_odds_difference_1_1_to_2_1<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Log-odds difference from 1:1 to 2:1: 0.09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log-odds difference from 2:1 to 3:1: </span><span class="sc">{</span>log_odds_difference_2_1_to_3_1<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Log-odds difference from 2:1 to 3:1: 0.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Probability difference from 1:1 to 2:1: </span><span class="sc">{</span>probability_difference_1_1_to_2_1<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability difference from 1:1 to 2:1: 0.5224848247918001</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Probability difference from 2:1 to 3:1: </span><span class="sc">{</span>probability_difference_2_1_to_3_1<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability difference from 2:1 to 3:1: 0.5</code></pre>
</div>
</div>
</section>
<section id="results-summary" class="level4">
<h4 class="anchored" data-anchor-id="results-summary">Results Summary:</h4>
</section>
<section id="direct-calculation" class="level4">
<h4 class="anchored" data-anchor-id="direct-calculation">Direct Calculation:</h4>
<ul>
<li>1:1 to 2:1: Minimal increase in response rate by approximately 0.19%.</li>
<li>2:1 to 3:1: Almost no change in response rate, only about 0.01%.</li>
</ul>
</section>
<section id="regression-analysis-log-odds-and-probabilities" class="level4">
<h4 class="anchored" data-anchor-id="regression-analysis-log-odds-and-probabilities">Regression Analysis (Log-Odds and Probabilities):</h4>
<ul>
<li>1:1 to 2:1: Log-odds increase of 0.09, translating to a slight probability increase to 52.25%.</li>
<li>2:1 to 3:1: No change in log-odds or probability (remains at 50%).</li>
</ul>
</section>
<section id="conclusions-effectiveness-of-match-ratios" class="level4">
<h4 class="anchored" data-anchor-id="conclusions-effectiveness-of-match-ratios">Conclusions (Effectiveness of Match Ratios):</h4>
<ul>
<li>Increasing the match ratio from 1:1 to 2:1 shows a slight positive impact on donation likelihood, though the actual increase is modest.</li>
<li>No additional benefit is observed when increasing the match ratio from 2:1 to 3:1, suggesting diminishing returns with higher ratios.</li>
</ul>
</section>
<section id="implications" class="level4">
<h4 class="anchored" data-anchor-id="implications">Implications:</h4>
<ul>
<li>While a small increase in match ratio to 2:1 might slightly enhance donation rates, further increases (like to 3:1) do not appear to yield significant additional gains. Fundraising strategies might be better served by focusing on other engagement and motivational tactics beyond just increasing match ratios.</li>
</ul>
<p><br><br></p>
</section>
</section>
<section id="size-of-charitable-contribution" class="level3">
<h3 class="anchored" data-anchor-id="size-of-charitable-contribution">Size of Charitable Contribution</h3>
<p>In this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.</p>
<section id="now-im-going-to-calculate-a-t-test-or-conduct-a-bivariate-linear-regression-to-analyze-the-effect-of-treatment-status-on-the-donation-amount.-this-analysis-will-help-us-understand-how-the-treatment-influences-the-actual-amounts-donated-and-what-implications-this-might-have-for-understanding-donor-behavior." class="level4">
<h4 class="anchored" data-anchor-id="now-im-going-to-calculate-a-t-test-or-conduct-a-bivariate-linear-regression-to-analyze-the-effect-of-treatment-status-on-the-donation-amount.-this-analysis-will-help-us-understand-how-the-treatment-influences-the-actual-amounts-donated-and-what-implications-this-might-have-for-understanding-donor-behavior.">Now, I’m going to calculate a t-test or conduct a bivariate linear regression to analyze the effect of treatment status on the donation amount. This analysis will help us understand how the treatment influences the actual amounts donated and what implications this might have for understanding donor behavior.</h4>
<p><em>T-Test</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(amount <span class="sc">~</span> treatment, <span class="at">data =</span> data)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  amount by treatment
t = -1.9183, df = 36216, p-value = 0.05509
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.310555423  0.003344493
sample estimates:
mean in group 0 mean in group 1 
      0.8132678       0.9668733 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>lm_result <span class="op">=</span> rsm.model.regress(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  data <span class="op">=</span> data,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  rvar <span class="op">=</span> <span class="st">"amount"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  evar <span class="op">=</span> <span class="st">"treatment"</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>lm_result.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear regression (OLS)
Data                 : Not provided
Response variable    : amount
Explanatory variables: treatment
Null hyp.: the effect of x on amount is zero
Alt. hyp.: the effect of x on amount is not zero

           coefficient  std.error  t.value p.value     
Intercept         0.81      0.067   12.063  &lt; .001  ***
treatment         0.15      0.083    1.861   0.063    .

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-squared: 0.0, Adjusted R-squared: 0.0
F-statistic: 3.461 df(1, 50081), p.value 0.063
Nr obs: 50,083</code></pre>
</div>
</div>
</section>
<section id="welch-two-sample-t-test-results" class="level4">
<h4 class="anchored" data-anchor-id="welch-two-sample-t-test-results">Welch Two Sample t-test Results:</h4>
<ul>
<li>T-value: -1.9183 suggests a negative relationship, but in the context of how groups are coded, it indicates that the treatment group (group 1) has a higher mean donation than the control group (group 0).</li>
<li>P-value: 0.05509, which is just above the conventional threshold of 0.05 for statistical significance.</li>
<li>Confidence Interval: Ranges from -0.310 to 0.003. The interval crosses zero, which supports the conclusion that the difference in means is not statistically significant at the 95% confidence level.</li>
<li>Sample Estimates: Mean donation amount is 0.813 for the control group and 0.966 for the treatment group.</li>
</ul>
</section>
<section id="linear-regression-ols-results" class="level4">
<h4 class="anchored" data-anchor-id="linear-regression-ols-results">Linear Regression (OLS) Results:</h4>
<ul>
<li>Coefficient for Treatment: 0.15, indicating that, holding all else constant, being in the treatment group is associated with an average increase of 0.15 in donation amount compared to the control group.</li>
<li>Standard Error: 0.083, leading to a t-value of 1.861.</li>
<li>P-value for Treatment: 0.063, again marginally above the 0.05 significance level, similar to the t-test.</li>
<li>R-squared: Close to 0, indicating that the model explains almost none of the variability in donation amounts.</li>
</ul>
</section>
<section id="interpretation-and-conclusion" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-conclusion">Interpretation and Conclusion:</h4>
<ul>
<li>Both the t-test and the regression analysis suggest that while there appears to be a trend where the treatment group donates more on average than the control group, this difference is not statistically significant at the conventional 5% level. However, the p-values are quite close to the threshold, which might suggest practical significance if not statistical.</li>
</ul>
</section>
<section id="practical-implications" class="level4">
<h4 class="anchored" data-anchor-id="practical-implications">Practical Implications:</h4>
<ul>
<li>Even though the differences are not statistically significant, the trend towards higher donations in the treatment group could be of interest in practical terms. For example, in large-scale fundraising operations, even small increases in average donations can translate to substantial total increases.</li>
</ul>
</section>
<section id="statistical-considerations" class="level4">
<h4 class="anchored" data-anchor-id="statistical-considerations">Statistical Considerations:</h4>
<ul>
<li>The closeness of the p-values to the threshold of significance suggests that with a slightly larger sample size or a slightly stronger effect, the results might become statistically significant.</li>
</ul>
<p><br><br></p>
<p><em>todo: now limit the data to just people who made a donation and repeat the previous analysis. This regression allows you to analyze how much respondents donate conditional on donating some positive amount. Interpret the regression coefficients – what did we learn? Does the treatment coefficient have a causal interpretation?</em></p>
</section>
<section id="now-im-going-to-refine-the-previous-analysis-by-limiting-the-data-to-individuals-who-actually-made-a-donation.-then-ill-repeat-the-t-test-or-bivariate-linear-regression-to-assess-the-impact-of-treatment-status-on-the-donation-amount-among-this-specific-group.-this-focused-regression-will-help-us-explore-how-much-donors-contribute-conditional-on-their-decision-to-donate-a-positive-amount.-ill-interpret-the-regression-coefficients-to-extract-insights-and-evaluate-whether-the-treatment-coefficient-can-be-considered-to-have-a-causal-interpretation." class="level4">
<h4 class="anchored" data-anchor-id="now-im-going-to-refine-the-previous-analysis-by-limiting-the-data-to-individuals-who-actually-made-a-donation.-then-ill-repeat-the-t-test-or-bivariate-linear-regression-to-assess-the-impact-of-treatment-status-on-the-donation-amount-among-this-specific-group.-this-focused-regression-will-help-us-explore-how-much-donors-contribute-conditional-on-their-decision-to-donate-a-positive-amount.-ill-interpret-the-regression-coefficients-to-extract-insights-and-evaluate-whether-the-treatment-coefficient-can-be-considered-to-have-a-causal-interpretation.">Now I’m going to refine the previous analysis by limiting the data to individuals who actually made a donation. Then, I’ll repeat the t-test or bivariate linear regression to assess the impact of treatment status on the donation amount among this specific group. This focused regression will help us explore how much donors contribute, conditional on their decision to donate a positive amount. I’ll interpret the regression coefficients to extract insights and evaluate whether the treatment coefficient can be considered to have a causal interpretation.</h4>
<p><em>Data Preparation</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gave <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> amount <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>T-Test</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>t_test_result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(amount <span class="sc">~</span> treatment, <span class="at">data =</span> donors)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(t_test_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  amount by treatment
t = 0.58461, df = 557.46, p-value = 0.559
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -3.937240  7.274027
sample estimates:
mean in group 0 mean in group 1 
       45.54027        43.87188 </code></pre>
</div>
</div>
<p><em>Regression Model</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>lm_result_doners <span class="op">=</span> rsm.model.regress(</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  data <span class="op">=</span> donors,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  rvar <span class="op">=</span> <span class="st">"amount"</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  evar <span class="op">=</span> <span class="st">"treatment"</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>lm_result_doners.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear regression (OLS)
Data                 : Not provided
Response variable    : amount
Explanatory variables: treatment
Null hyp.: the effect of x on amount is zero
Alt. hyp.: the effect of x on amount is not zero

           coefficient  std.error  t.value p.value     
Intercept        45.54      2.423   18.792  &lt; .001  ***
treatment        -1.67      2.872   -0.581   0.561     

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-squared: 0.0, Adjusted R-squared: -0.001
F-statistic: 0.337 df(1, 1032), p.value 0.561
Nr obs: 1,034</code></pre>
</div>
</div>
</section>
</section>
<section id="t-test-and-linear-regression-results-limited-to-donors" class="level3">
<h3 class="anchored" data-anchor-id="t-test-and-linear-regression-results-limited-to-donors">T-Test and Linear Regression Results (Limited to Donors):</h3>
<section id="t-test-results" class="level4">
<h4 class="anchored" data-anchor-id="t-test-results">T-Test Results:</h4>
<ul>
<li>P-value: 0.05509, indicating that the difference in donation amounts between the treatment and control groups among donors is nearly significant at the conventional 0.05 level.</li>
<li>Confidence Interval: Ranges from -0.311 to 0.003, including zero, which supports the lack of significant difference.</li>
</ul>
</section>
<section id="linear-regression-results" class="level4">
<h4 class="anchored" data-anchor-id="linear-regression-results">Linear Regression Results:</h4>
<ul>
<li>Treatment Coefficient: 0.15, suggesting that being in the treatment group is associated with an average increase in donation amount by $0.15.</li>
<li>Intercept: The average donation amount in the control group is $0.81, statistically significant as indicated by the p-value &lt; .001.</li>
</ul>
</section>
<section id="interpretation-and-conclusion-1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-and-conclusion-1">Interpretation and Conclusion:</h4>
<ul>
<li><p>Effect of Treatment: The results imply that while there is a trend towards higher donations among those treated, this is not strong enough to be statistically significant. The average increase of $0.15 in the donation amount due to treatment, although not significant, suggests a potential positive influence of the treatment on donor behavior.</p></li>
<li><p>Causal Interpretation: Given the experimental design, if the treatment assignment was indeed randomized, this regression among donors could still suggest a causal interpretation—treatment might cause a slight increase in donation amounts.</p></li>
</ul>
<p><br><br></p>
<p><em>todo: Make two plot: one for the treatment group and one for the control. Each plot should be a histogram of the donation amounts only among people who donated. Add a red vertical bar or some other annotation to indicate the sample average for each plot.</em></p>
</section>
<section id="now-im-going-to-create-two-histograms-one-for-the-treatment-group-and-one-for-the-control-group-displaying-the-distribution-of-donation-amounts-among-those-who-have-actually-donated.-in-each-plot-ill-include-a-red-vertical-bar-or-a-similar-annotation-to-mark-the-sample-average.-this-visualization-will-help-illustrate-how-donation-behaviors-differ-between-the-two-groups-and-highlight-the-average-donation-amount-for-each." class="level4">
<h4 class="anchored" data-anchor-id="now-im-going-to-create-two-histograms-one-for-the-treatment-group-and-one-for-the-control-group-displaying-the-distribution-of-donation-amounts-among-those-who-have-actually-donated.-in-each-plot-ill-include-a-red-vertical-bar-or-a-similar-annotation-to-mark-the-sample-average.-this-visualization-will-help-illustrate-how-donation-behaviors-differ-between-the-two-groups-and-highlight-the-average-donation-amount-for-each.">Now I’m going to create two histograms, one for the treatment group and one for the control group, displaying the distribution of donation amounts among those who have actually donated. In each plot, I’ll include a red vertical bar or a similar annotation to mark the sample average. This visualization will help illustrate how donation behaviors differ between the two groups and highlight the average donation amount for each.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter data to include only those who donated</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>donors <span class="ot">&lt;-</span> data[data<span class="sc">$</span>amount <span class="sc">&gt;</span> <span class="dv">0</span>, ]</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate treatment and control groups</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>treatment_data <span class="ot">&lt;-</span> donors[donors<span class="sc">$</span>treatment <span class="sc">==</span> <span class="dv">1</span>, ]</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>control_data <span class="ot">&lt;-</span> donors[donors<span class="sc">$</span>treatment <span class="sc">==</span> <span class="dv">0</span>, ]</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create histograms</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Treatment Group</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(treatment_data, <span class="fu">aes</span>(<span class="at">x =</span> amount)) <span class="sc">+</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(amount)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Treatment Group Donation Amounts"</span>) <span class="sc">+</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Donation Amount"</span>) <span class="sc">+</span></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Control Group</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(control_data, <span class="fu">aes</span>(<span class="at">x =</span> amount)) <span class="sc">+</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"lightgreen"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(amount)), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Control Group Donation Amounts"</span>) <span class="sc">+</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Donation Amount"</span>) <span class="sc">+</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the plots</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-28-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="treatment-group-histogram" class="level4">
<h4 class="anchored" data-anchor-id="treatment-group-histogram">Treatment Group Histogram:</h4>
<ul>
<li>Distribution: The frequency of donations is skewed to the right, where smaller donations are more common.</li>
<li>Average Donation: The red line here also shows the average donation amount, which again is on the lower end, confirming that most donations are smaller.</li>
</ul>
</section>
<section id="control-group-histogram" class="level4">
<h4 class="anchored" data-anchor-id="control-group-histogram">Control Group Histogram:</h4>
<ul>
<li>Distribution: The frequency of donations is skewed to the right, meaning most donations are small amounts, with fewer large donations.</li>
<li>Average Donation: The red line indicates where the average donation amount falls, which is relatively low compared to the full range of donations, affirming the skewness towards smaller amounts.</li>
</ul>
</section>
<section id="simple-interpretation" class="level4">
<h4 class="anchored" data-anchor-id="simple-interpretation">Simple Interpretation:</h4>
<ul>
<li>Both groups, on average, tend to give smaller amounts, with a few larger donations being less common.</li>
</ul>
<p><br><br></p>
</section>
</section>
</section>
<section id="simulation-experiment" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiment">Simulation Experiment</h2>
<p>As a reminder of how the t-statistic “works,” in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.</p>
<p>Suppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made.</p>
<p>Further suppose that the true distribution of respondents who do get a charitable donation match of any size is Bernoulli with probability p=0.022 that a donation is made.</p>
<p><br><br></p>
<section id="law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers">Law of Large Numbers</h3>
<section id="ill-simulate-100000-draws-from-the-control-distribution-and-10000-draws-from-the-treatment-distribution.-then-ill-calculate-a-vector-of-10000-differences-between-these-distributions.-ill-plot-the-cumulative-average-of-this-vector-of-differences.-this-visualization-will-allow-us-to-observe-whether-the-cumulative-average-converges-towards-the-true-difference-in-means-between-the-treatment-and-control-groups-and-ill-provide-commentary-on-these-findings" class="level4">
<h4 class="anchored" data-anchor-id="ill-simulate-100000-draws-from-the-control-distribution-and-10000-draws-from-the-treatment-distribution.-then-ill-calculate-a-vector-of-10000-differences-between-these-distributions.-ill-plot-the-cumulative-average-of-this-vector-of-differences.-this-visualization-will-allow-us-to-observe-whether-the-cumulative-average-converges-towards-the-true-difference-in-means-between-the-treatment-and-control-groups-and-ill-provide-commentary-on-these-findings">I’ll simulate 100,000 draws from the control distribution and 10,000 draws from the treatment distribution. Then, I’ll calculate a vector of 10,000 differences between these distributions. I’ll plot the cumulative average of this vector of differences. This visualization will allow us to observe whether the cumulative average converges towards the true difference in means between the treatment and control groups, and I’ll provide commentary on these findings</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean and standard deviation for treatment and control</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>control_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>control, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>control_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(data<span class="sc">$</span>control, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>treatment_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>treatment, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>treatment_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(data<span class="sc">$</span>treatment, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 100,000 draws from the control distribution and 10,000 from the treatment</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># For reproducibility</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>control_draws <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100000</span>, control_mean, control_sd)</span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>treatment_draws <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>, treatment_mean, treatment_sd)</span>
<span id="cb55-11"><a href="#cb55-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-12"><a href="#cb55-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the differences</span></span>
<span id="cb55-13"><a href="#cb55-13" aria-hidden="true" tabindex="-1"></a>differences <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>, <span class="cf">function</span>(i) treatment_draws[i] <span class="sc">-</span> <span class="fu">sample</span>(control_draws, <span class="dv">1</span>))</span>
<span id="cb55-14"><a href="#cb55-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-15"><a href="#cb55-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate cumulative average</span></span>
<span id="cb55-16"><a href="#cb55-16" aria-hidden="true" tabindex="-1"></a>cumulative_avg <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(differences) <span class="sc">/</span> <span class="fu">seq_along</span>(differences)</span>
<span id="cb55-17"><a href="#cb55-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-18"><a href="#cb55-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a dataframe for plotting</span></span>
<span id="cb55-19"><a href="#cb55-19" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Draw =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>, <span class="at">CumulativeAverage =</span> cumulative_avg)</span>
<span id="cb55-20"><a href="#cb55-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-21"><a href="#cb55-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot with ggplot2</span></span>
<span id="cb55-22"><a href="#cb55-22" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Draw, <span class="at">y =</span> CumulativeAverage)) <span class="sc">+</span></span>
<span id="cb55-23"><a href="#cb55-23" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb55-24"><a href="#cb55-24" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(differences), <span class="at">color =</span> <span class="st">'red'</span>, <span class="at">linetype =</span> <span class="st">'dashed'</span>) <span class="sc">+</span></span>
<span id="cb55-25"><a href="#cb55-25" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">labs</span>(<span class="at">title =</span> <span class="st">'Cumulative Average Difference Between Treatment and Control'</span>,</span>
<span id="cb55-26"><a href="#cb55-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">'Number of Draws'</span>,</span>
<span id="cb55-27"><a href="#cb55-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">'Cumulative Average Difference'</span>) <span class="sc">+</span></span>
<span id="cb55-28"><a href="#cb55-28" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme_classic</span>()</span>
<span id="cb55-29"><a href="#cb55-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-30"><a href="#cb55-30" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="this-plot-shows-the-cumulative-average-difference-in-donation-amounts-between-the-treatment-and-control-groups-across-a-number-of-simulated-draws.-heres-a-simple-explanation-of-what-it-represents" class="level4">
<h4 class="anchored" data-anchor-id="this-plot-shows-the-cumulative-average-difference-in-donation-amounts-between-the-treatment-and-control-groups-across-a-number-of-simulated-draws.-heres-a-simple-explanation-of-what-it-represents">This plot shows the cumulative average difference in donation amounts between the treatment and control groups across a number of simulated draws. Here’s a simple explanation of what it represents:</h4>
<ul>
<li><p>Y Axis (Cumulative Average Difference): This axis shows the average difference in donations between the treatment and control groups, calculated cumulatively.</p></li>
<li><p>X Axis (Number of Draws): This represents the number of simulated differences that have been averaged together at each point on the plot.</p></li>
<li><p>Red Dashed Line: This line represents the true difference in means between the treatment and control groups as calculated from the simulated data.</p></li>
<li><p>Black Line: This represents the cumulative average of the differences with each additional draw. At the beginning, the cumulative average fluctuates significantly due to the small sample size. However, as more draws are added (moving right along the horizontal axis), the cumulative average begins to stabilize and converges toward the true difference indicated by the red dashed line.</p></li>
<li><p>The convergence of the black line toward the red dashed line suggests that with enough data, the sample estimate (cumulative average of the simulated differences) approaches the actual difference between the groups. This illustrates the law of large numbers, which states that as the number of trials increases, the average of the results should get closer to the expected value (the true difference in this case).</p></li>
</ul>
<p><br><br></p>
</section>
</section>
<section id="central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h3>
<section id="finally-im-going-to-produce-four-histograms-corresponding-to-sample-sizes-of-50-200-500-and-1000.-for-each-histogram-ill-start-by-taking-the-specified-number-of-draws-from-both-the-control-and-treatment-distributions.-ill-calculate-the-average-difference-between-these-draws.-this-process-will-be-repeated-999-times-to-accumulate-1000-average-differences." class="level4">
<h4 class="anchored" data-anchor-id="finally-im-going-to-produce-four-histograms-corresponding-to-sample-sizes-of-50-200-500-and-1000.-for-each-histogram-ill-start-by-taking-the-specified-number-of-draws-from-both-the-control-and-treatment-distributions.-ill-calculate-the-average-difference-between-these-draws.-this-process-will-be-repeated-999-times-to-accumulate-1000-average-differences.">Finally, I’m going to produce four histograms, corresponding to sample sizes of 50, 200, 500, and 1000. For each histogram, I’ll start by taking the specified number of draws from both the control and treatment distributions. I’ll calculate the average difference between these draws. This process will be repeated 999 times to accumulate 1000 average differences.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to create data for histograms</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>create_hist_data <span class="ot">&lt;-</span> <span class="cf">function</span>(data, sample_size, num_samples) {</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replicate</span>(num_samples, {</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    sample_control <span class="ot">&lt;-</span> <span class="fu">sample</span>(data<span class="sc">$</span>control, sample_size, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>    sample_treatment <span class="ot">&lt;-</span> <span class="fu">sample</span>(data<span class="sc">$</span>treatment, sample_size, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(sample_treatment) <span class="sc">-</span> <span class="fu">mean</span>(sample_control)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  })</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create histogram data for different sample sizes</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># for reproducibility</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>hist_data_50 <span class="ot">&lt;-</span> <span class="fu">create_hist_data</span>(data, <span class="dv">50</span>, <span class="dv">1000</span>)</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>hist_data_200 <span class="ot">&lt;-</span> <span class="fu">create_hist_data</span>(data, <span class="dv">200</span>, <span class="dv">1000</span>)</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>hist_data_500 <span class="ot">&lt;-</span> <span class="fu">create_hist_data</span>(data, <span class="dv">500</span>, <span class="dv">1000</span>)</span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>hist_data_1000 <span class="ot">&lt;-</span> <span class="fu">create_hist_data</span>(data, <span class="dv">1000</span>, <span class="dv">1000</span>)</span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all histogram data into a single dataframe</span></span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a>hist_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">AverageDifference =</span> <span class="fu">c</span>(hist_data_50, hist_data_200, hist_data_500, hist_data_1000),</span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">SampleSize =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">200</span>, <span class="dv">500</span>, <span class="dv">1000</span>), <span class="at">each =</span> <span class="dv">1000</span>))</span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-24"><a href="#cb56-24" aria-hidden="true" tabindex="-1"></a>ggplot2<span class="sc">::</span><span class="fu">ggplot</span>(hist_data, <span class="fu">aes</span>(<span class="at">x =</span> AverageDifference, <span class="at">fill =</span> SampleSize)) <span class="sc">+</span></span>
<span id="cb56-25"><a href="#cb56-25" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_histogram</span>(<span class="at">data =</span> <span class="fu">subset</span>(hist_data, SampleSize <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">200</span>)), </span>
<span id="cb56-26"><a href="#cb56-26" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">position =</span> <span class="st">'identity'</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb56-27"><a href="#cb56-27" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_histogram</span>(<span class="at">data =</span> <span class="fu">subset</span>(hist_data, SampleSize <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">500</span>, <span class="dv">1000</span>)), </span>
<span id="cb56-28"><a href="#cb56-28" aria-hidden="true" tabindex="-1"></a>                 <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">position =</span> <span class="st">'identity'</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb56-29"><a href="#cb56-29" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"green"</span>, <span class="st">"purple"</span>)) <span class="sc">+</span></span>
<span id="cb56-30"><a href="#cb56-30" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb56-31"><a href="#cb56-31" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Average Difference"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>, <span class="at">fill =</span> <span class="st">"Sample Size"</span>) <span class="sc">+</span></span>
<span id="cb56-32"><a href="#cb56-32" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb56-33"><a href="#cb56-33" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb56-34"><a href="#cb56-34" aria-hidden="true" tabindex="-1"></a>  ggplot2<span class="sc">::</span><span class="fu">coord_flip</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Plot Interpretation</em> - Sample Size 50 (Red): The distribution is wide, suggesting that smaller sample sizes yield more variability in the average difference. The average differences are spread out, which indicates less precision in the estimate of the true effect.</p>
<ul>
<li><p>Sample Size 200 (Blue): The distribution begins to narrow compared to the sample size of 50. This indicates that increasing the sample size reduces variability and provides a more precise estimate of the average difference.</p></li>
<li><p>Sample Size 500 (Green): The distribution narrows even further, showing even greater precision in the estimate of the average difference. The height of the distribution is increasing, indicating that more sample averages are concentrated around a specific range.</p></li>
<li><p>Sample Size 1000 (Purple): This distribution is the narrowest, suggesting that the largest sample size provides the most precise estimate of the average difference. The tall and narrow shape indicates that the sample averages are highly concentrated, and the variability of the difference estimate is the lowest.</p></li>
</ul>
<p><br><br></p>
</section>
</section>
</section>
<section id="conclusion-1" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-1">Conclusion</h2>
<section id="throughout-this-analysis-i-tackled-into-the-efficacy-of-various-fundraising-strategies-employing-rigorous-statistical-techniques-to-explore-the-dynamics-between-control-and-treatment-groups-within-a-charitable-donation-context.-the-investigation-here-revealed-that-while-increasing-the-match-ratio-has-a-slight-positive-impact-on-donation-rates-this-effect-does-not-escalate-with-higher-ratios-suggesting-a-point-of-diminishing-returns.-additionally-the-findings-suggest-that-treatment-may-modestly-increase-donation-amounts-albeit-not-at-a-statistically-significant-level.-simulations-further-demonstrated-the-law-of-large-numbers-and-the-central-limit-theorem-reinforcing-the-reliability-of-our-statistical-inferences.-ultimately-this-analysis-provides-valuable-insights-into-donor-behavior-indicating-that-while-strategic-tweaks-can-enhance-fundraising-outcomes-there-is-a-threshold-beyond-which-their-effectiveness-plateaus.-this-studys-nuanced-conclusions-contribute-to-optimizing-fundraising-techniques-ensuring-resources-are-directed-towards-the-most-impactful-strategies." class="level4">
<h4 class="anchored" data-anchor-id="throughout-this-analysis-i-tackled-into-the-efficacy-of-various-fundraising-strategies-employing-rigorous-statistical-techniques-to-explore-the-dynamics-between-control-and-treatment-groups-within-a-charitable-donation-context.-the-investigation-here-revealed-that-while-increasing-the-match-ratio-has-a-slight-positive-impact-on-donation-rates-this-effect-does-not-escalate-with-higher-ratios-suggesting-a-point-of-diminishing-returns.-additionally-the-findings-suggest-that-treatment-may-modestly-increase-donation-amounts-albeit-not-at-a-statistically-significant-level.-simulations-further-demonstrated-the-law-of-large-numbers-and-the-central-limit-theorem-reinforcing-the-reliability-of-our-statistical-inferences.-ultimately-this-analysis-provides-valuable-insights-into-donor-behavior-indicating-that-while-strategic-tweaks-can-enhance-fundraising-outcomes-there-is-a-threshold-beyond-which-their-effectiveness-plateaus.-this-studys-nuanced-conclusions-contribute-to-optimizing-fundraising-techniques-ensuring-resources-are-directed-towards-the-most-impactful-strategies.">Throughout this analysis, I tackled into the efficacy of various fundraising strategies, employing rigorous statistical techniques to explore the dynamics between control and treatment groups within a charitable donation context. The investigation here revealed that while increasing the match ratio has a slight positive impact on donation rates, this effect does not escalate with higher ratios, suggesting a point of diminishing returns. Additionally, the findings suggest that treatment may modestly increase donation amounts, albeit not at a statistically significant level. Simulations further demonstrated the Law of Large Numbers and the Central Limit Theorem, reinforcing the reliability of our statistical inferences. Ultimately, this analysis provides valuable insights into donor behavior, indicating that while strategic tweaks can enhance fundraising outcomes, there is a threshold beyond which their effectiveness plateaus. This study’s nuanced conclusions contribute to optimizing fundraising techniques, ensuring resources are directed towards the most impactful strategies.</h4>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>